GetARoom/GetARoom.UI.Web.Administration/Controllers/AssetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GetARoom.DAL;

namespace GetARoom.UI.Web.Administration.Controllers
{
    public class AssetsController : Controller
    {
        private GetARoomEntities db = new GetARoomEntities();

        // GET: Assets
        public ActionResult Index()
        {
            return View(db.Asset.ToList());
        }

        // GET: Assets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Asset asset = db.Asset.Find(id);
            if (asset == null)
            {
                return HttpNotFound();
            }
            return View(asset);
        }

        // GET: Assets/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Assets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AssetId,AssetName")] Asset asset)
        {
            if (ModelState.IsValid)
            {
                db.Asset.Add(asset);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(asset);
        }

        // GET: Assets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Asset asset = db.Asset.Find(id);
            if (asset == null)
            {
                return HttpNotFound();
            }
            return View(asset);
        }

        // POST: Assets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AssetId,AssetName")] Asset asset)
        {
            if (ModelState.IsValid)
            {
                db.Entry(asset).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(asset);
        }

        // GET: Assets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Asset asset = db.Asset.Find(id);
            if (asset == null)
            {
                return HttpNotFound();
            }
            return View(asset);
        }

        // POST: Assets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Asset asset = db.Asset.Find(id);
            db.Asset.Remove(asset);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GetARoom/GetARoom.UI.Web.Administration/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GetARoom.DAL;

namespace GetARoom.UI.Web.Administration.Controllers
{
    public class BookingsController : Controller
    {
        private GetARoomEntities db = new GetARoomEntities();

        // GET: Bookings
        public ActionResult Index()
        {
            var booking = db.Booking.Include(b => b.Room).Include(b => b.User);
            return View(booking.ToList());
        }

        // GET: Bookings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Booking.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // GET: Bookings/Create
        public ActionResult Create()
        {
            ViewBag.RoomId = new SelectList(db.Room, "RoomId", "Roomdescription");
            ViewBag.UserId = new SelectList(db.User, "UserId", "UserId");
            return View();
        }

        // POST: Bookings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BookingId,UserId,RoomId,BookingDate,BookingDateFrom,BookingDateTo")] Booking booking)
        {
            if (ModelState.IsValid)
            {
                db.Booking.Add(booking);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.RoomId = new SelectList(db.Room, "RoomId", "Roomdescription", booking.RoomId);
            ViewBag.UserId = new SelectList(db.User, "UserId", "UserId", booking.UserId);
            return View(booking);
        }

        // GET: Bookings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Booking.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            ViewBag.RoomId = new SelectList(db.Room, "RoomId", "Roomdescription", booking.RoomId);
            ViewBag.UserId = new SelectList(db.User, "UserId", "UserId", booking.UserId);
            return View(booking);
        }

        // POST: Bookings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BookingId,UserId,RoomId,BookingDate,BookingDateFrom,BookingDateTo")] Booking booking)
        {
            if (ModelState.IsValid)
            {
                db.Entry(booking).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.RoomId = new SelectList(db.Room, "RoomId", "Roomdescription", booking.RoomId);
            ViewBag.UserId = new SelectList(db.User, "UserId", "UserId", booking.UserId);
            return View(booking);
        }

        // GET: Bookings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Booking.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Booking booking = db.Booking.Find(id);
            db.Booking.Remove(booking);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GetARoom/GetARoom.UI.Web.Administration/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GetARoom.UI.Web.Administration.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

      
    }
}

GetARoom/GetARoom.UI.Web.Administration/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Get a Room administration page.</h1>
    <p class="lead">This page is intended for an admin of the GetARoom page.</p>

</div>

<div class="row">
    <div class="col-md-4" style="border:1px solid black; border-radius:8px 8px">
        <h2>Assets</h2>
        <p>
            You can change the Asset objects here.
            - Contains (id, name)
        </p>
        <center>
            <p style="font-size:20px; font-weight:bold;border:10px solid #999999;
        width:30%; background-color:#BBBBBB; border-radius: 10px 10px;">
                @Html.ActionLink("Asset", "Index", "Assets")
            </p>
        </center>
    </div>
    <div class="col-md-4" style="border:1px solid black; border-radius:8px 8px">
        <h2>Addresses</h2>
        <p>
            You can change the Address objects here.
            - Contains (postal code, street, number , bus)
        </p>
        <center>
            <p style="font-size:20px; font-weight:bold;border:10px solid #999999;
        width:50%; background-color:#BBBBBB; border-radius: 10px 10px">
                @Html.ActionLink("Addresses", "Index", "Addresses")
            </p>
        </center>
    </div>

    <div class="col-md-4" style="border:1px solid black; border-radius:8px 8px">
        <h2>Amenities</h2>
        <p>
            You can change the Address objects here.
            - Contains (name and description)
        </p>
        <center>
            <p style="font-size:20px; font-weight:bold;border:10px solid #999999;
        width:50%; background-color:#BBBBBB; border-radius: 10px 10px">
                @Html.ActionLink("Amenities", "Index", "Amenities")
            </p>
        </center>
    </div>

    <div class="col-md-4" style="border:1px solid black; border-radius:8px 8px">
        <h2>Bookings</h2>
        <p>
            You can change the Address objects here.
            - Contains (from, to, now, room)
        </p>
        <center>
            <p style="font-size:20px; font-weight:bold;border:10px solid #999999;
        width:50%; background-color:#BBBBBB; border-radius: 10px 10px">
                @Html.ActionLink("Booking", "Index", "Bookings")
            </p>
        </center>
    </div>
    <div class="col-md-4" style="border:1px solid black; border-radius:8px 8px">
        <h2>Geolocations</h2>
        <p>
            You can change the Address objects here.
            - Contains (lat and long)
        </p>
        <center>
            <p style="font-size:20px; font-weight:bold;border:10px solid #999999;
        width:50%; background-color:#BBBBBB; border-radius: 10px 10px">
                @Html.ActionLink("Geolocations", "Index", "Geolocations")
            </p>
        </center>
    </div>

    <div class="col-md-4" style="border:1px solid black; border-radius:8px 8px">
        <h2>Hotels</h2>
        <p>
            You can change the Hotels objects here.
            - Contains (lat and long)
        </p>
        <center>
            <p style="font-size:20px; font-weight:bold;border:10px solid #999999;
        width:50%; background-color:#BBBBBB; border-radius: 10px 10px">
                @Html.ActionLink("Hotels", "Index", "Hotels")
            </p>
        </center>
    </div>
    <div class="col-md-4" style="border:1px solid black; border-radius:8px 8px">
        <h2>Locations</h2>
        <p>
            You can change the Hotels objects here.
            - Contains (lat and long)
        </p>
        <center>
            <p style="font-size:20px; font-weight:bold;border:10px solid #999999;
        width:50%; background-color:#BBBBBB; border-radius: 10px 10px">
                @Html.ActionLink("Locations", "Index", "Locations")
            </p>
        </center>
    </div>

    <div class="col-md-4" style="border:1px solid black; border-radius:8px 8px">
        <h2>Payments</h2>
        <p>
            You can change the Payments objects here.
            - Contains (lat and long)
        </p>
        <center>
            <p style="font-size:20px; font-weight:bold;border:10px solid #999999;
        width:50%; background-color:#BBBBBB; border-radius: 10px 10px">
                @Html.ActionLink("Payments", "Index", "Payments")
            </p>
        </center>
    </div>

    <div class="col-md-4" style="border:1px solid black; border-radius:8px 8px">
        <h2>Person</h2>
        <p>
            You can change the Person objects here.
            - Contains (lat and long)
        </p>
        <center>
            <p style="font-size:20px; font-weight:bold;border:10px solid #999999;
        width:50%; background-color:#BBBBBB; border-radius: 10px 10px">
                @Html.ActionLink("Person", "Index", "Person")
            </p>
        </center>
    </div>
    <div class="col-md-4" style="border:1px solid black; border-radius:8px 8px">
        <h2>Pictures</h2>
        <p>
            You can change the Pictures objects here.
            - Contains (lat and long)
        </p>
        <center>
            <p style="font-size:20px; font-weight:bold;border:10px solid #999999;
        width:50%; background-color:#BBBBBB; border-radius: 10px 10px">
                @Html.ActionLink("Pictures", "Index", "Pictures")
            </p>
        </center>
    </div>
</div>